embeddings {
  tensor_name: "item_id:06062"
  metadata_path: "06062/item_id\\metadata.tsv"
  tensor_path: "06062/item_id\\tensors.tsv"
}
embeddings {
  tensor_name: "dept_id:06062"
  metadata_path: "06062/dept_id\\metadata.tsv"
  tensor_path: "06062/dept_id\\tensors.tsv"
}
embeddings {
  tensor_name: "store_id:06062"
  metadata_path: "06062/store_id\\metadata.tsv"
  tensor_path: "06062/store_id\\tensors.tsv"
}
